import type { Metadata } from "next";
import "@/app/styles/globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import DatabaseStatusIndicator from "@/components/DatabaseStatusIndicator/DatabaseStatusIndicator";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <DatabaseStatusIndicator />
      {children}
      </body>
    </html>
  );
}
